#!/bin/sh
# Build a CS fmu
# Usage: build_fmu directory

if [ $# -ne 1 ]; then
   echo "Usage: $0 directory"
   exit 2
fi

directory=$1

# Error checking
if [ ! -d $directory ]; then
   echo "$0: directory $directory does not exist"
   exit 4
fi

csInclude="-DFMI_COSIMULATION -I../../include"

case "`uname -s`" in
     CYGWIN*) arch=win
     	      sharedLibrarySuffix=dll;;
     Darwin)  arch=darwin
     	      sharedLibrarySuffix=dylib;;
     Linux)   arch=linux
     	      pic=-fPIC
     	      sharedLibrarySuffix=so;;
esac     

# Number of bits, default to 64
bits=64
case "`uname -m`" in
     *64)      bits=64;;
     *32)      bits=32;;
     *i[3-6]86) bits=32;;
esac

# Uncomment the next line to force building 32-bit
#bits=32
# See also ../Makefile

if [ $arch = linux -a $bits = 32 ]; then
    CBITSFLAGS=-m32
fi

set -x
(cd $directory; \
    make dirclean; \
    make ARCH=${arch}${bits} CBITSFLAGS=${CBITSFLAGS} CSORME=cs CSORME_INCLUDE="${csInclude}" PIC=${pic} SHARED_LIBRARY_SUFFIX=${sharedLibrarySuffix} $directory.fmu)
